### ISSUE TITLE
[Customizable key bindings] 

### ISSUE THREAD

**Issue by merinoalex** [avi12/skillshare-player-control#7]
### What is your feature request?

I use a Latin American layout for my keyboard and sadly can't use the key bindings `<` `>` to change speed. Is there a way to change them or add support to do it?

Thanks.

**Comment by avi12** [comment]
The goal of these shortcuts is to mimic the YouTube player experience
How do you currently speed up or slow down videos on YouTube?

**Comment by merinoalex** [comment]
Good question, I actually had to manually click on the player icon and change it from there. I looked it up and apparently `SHIFT` + `,`  and `SHIFT` + `.` work to slow down or speed up in steps, respectively. I don't think skillshare-player-control supports this since it won't work.

I found out this is a common issue (at least among people who use Spanish keyboard layouts — be it Latin American or European Spanish) since `<` and `>` share only one physical key, while `,` and `.` are separated. [Here's the keyboard layout for reference.](https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/KB_Spanish.svg/2880px-KB_Spanish.svg.png)

Using `<` or `SHIFT` + < (to produce `>`) also doesn't work for either YouTube or skillshare-player-control for some reason.

**Comment by merinoalex** [comment]
Sorry, I closed the issue like a fool.

**Comment by avi12** [comment]
> I don't think skillshare-player-control supports this since it won't work.

It should be supporting it as expected
This is the related piece of code:

https://github.com/avi12/skillshare-player-control/blob/eafc3d8ce07bf5a12f21451753d59a1d9ee5b3d2/src/cs-utils/skillshare-content-script-hotkeys.ts#L130-L145

It uses [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code):
> The KeyboardEvent.code property represents a **physical** key on the keyboard (as opposed to the character generated by pressing the key).

To make sure we're on the same page, press <kbd>Shift</kbd>+<kbd>,</kbd>/<kbd>.</kbd> on https://www.toptal.com/developers/keycode and tell me what's on `event.code`

**Comment by merinoalex** [comment]
Okay, I tried it again and it worked now. Maybe I was doing something wrong, but just as you said, it does support <kbd>SHIFT</kbd> + <kbd>,</kbd>/<kbd>.</kbd>

<kbd>SHIFT</kbd> + <kbd>,</kbd> produces key code 188 and and <kbd>SHIFT</kbd> + <kbd>.</kbd> produces 190.

Thanks for clearing this out and sorry to bug you on this.

**Comment by avi12** [comment]
> <kbd>SHIFT</kbd> + <kbd>,</kbd> produces key code 188 and and <kbd>SHIFT</kbd> + <kbd>.</kbd> produces 190.

I meant `event.code`, not `event.which` which is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which)

> Thanks for clearing this out and sorry to bug you on this.

No worries, glad the issue got resolved 🙂
