### ISSUE TITLE
[Bug] Play/pause button doesn't work

### ISSUE THREAD

**Issue by niccololamolo** [avi12/skillshare-player-control#8]
### Describe the bug

Pause/play button doesn't work. 

### How to reproduce

use video player

### Expected behavior

play/pause button is the most important button, it should work

### What browser(s) can you reproduce the issue on?

Chrome

### What OS does it occur on?

macOS

### What's the version you're running?

2.0.1

**Comment by avi12** [comment]
It should work once you focus on the video player

**Comment by niccololamolo** [comment]
It does not work at all and "play/pause" button doesn't appear on hotkeys map either
<img width="620" alt="Screenshot 2023-05-31 at 11 47 37 AM" src="https://github.com/avi12/skillshare-player-control/assets/114865513/af6931b9-1f93-4188-96a4-06b63e01049b">

**Comment by avi12** [comment]
I must've forgotten to list that shortcut, my bad

**Comment by avi12** [comment]
Later today I'll give a deeper look into it as well as list the shortcut

**Comment by niccololamolo** [comment]
Thanks. I find it very odd that the Skillshare video player lacks such basic functionality.
Especially given that they have so many courses that purport to train people to build such functionality.

I wonder how many customers Skillshare has missed out on because their player sucks?

Pretty cool that people like you are there to fill the gaps though

**Comment by avi12** [comment]
Indeed, I made this extension after I discovered that no one else made one 😁
If you can, I'd love it if you could [donate](https://paypal.me/avi12) to me :)

**Comment by avi12** [comment]
Let me know if this version works for you: [skillshare-player-control-2.0.4.zip](https://github.com/avi12/skillshare-player-control/files/11618792/skillshare-player-control-2.0.4.zip)
[How to install](https://www.youtube.com/watch?v=aMxenpDBvN4)

**Comment by niccololamolo** [comment]
Works now, well done

**Comment by avi12** [comment]
Still got one bug to fix, which is focusing on the video player when pressing <kbd>Shift</kbd>+<kbd>N</kbd>/<kbd>P</kbd>
Skillshare is giving me a great headache with it lol
Sadly my day is over, but hopefully, I'll continue tomorrow and push the update ASAP

**Comment by avi12** [comment]
I managed to fix this bug and tested on Chrome, Edge, and Opera successfully, but Firefox is currently the outlier in which it doesn't work correctly ¯\_(ツ)_/¯
Once I manage to fix it on Firefox, I will push the updates
